### DISCUSSION TITLE
Loxilb LB setup issue

### DISCUSSION THREAD

**Discussion by chugh50** [loxilb-io/loxilb#941] [Q&A] [answered]
i have deploy loxilb.yaml and kube-loxilb.yaml and my pods are running fine when i see through kubectl get po
but when i try to look into the logs of kube-loxilb i am seeing this error 

1 loadbalancer.go:2357] loxilb-lb(10.10.19.69): set-role-master(llb-inst0:true) - OK
I0120 11:02:52.102178       1 loadbalancer.go:2428] loxilb-lb(20.20.19.69): set-role-master(llb-inst0:true) - OK
I0120 11:02:52.106160       1 loadbalancer.go:2476] loxilb(20.20.19.69) set-bgp-global success
E0120 11:02:54.448712       1 loadbalancer.go:370] Error syncing LoadBalancer {default amf-loxilb-service}, requeuing. Error: no active endpoints
E0120 11:03:10.449524       1 loadbalancer.go:370] Error syncing LoadBalancer {default amf-loxilb-service}, requeuing. Error: no active endpoints

"Error syncing LoadBalancer {default amf-loxilb-service}, requeuing. Error: no active endpoints"

So getting error no active endpoints for amf-loxilb-service 
amf-loxilb-service is the kubernetes service i used to expose the loadbalancer to outer world by provivding external ip and port and i also mentioned the correct selector in this .Also verify that the selector labels are correct and pointing to correct endpoint but still not able to resolve this issue .If anyone know this issue please help

**Comment by backguynn** [comment, marked as answer]
Hello. 
The LoadBalancer service uses a Nodeport as its endpoint.

First, check whether your K8s node has the following label: `node.kubernetes.io/exclude-from-external-load-balancers`.
If the node has that label, remove it. 
Any node with that label is excluded from the endpoints.

If the node does not have that label but you’re still encountering the same error, please share the YAML file for the amf-loxilb-service you created. I'll take a look at it.

**Reply by chugh50** [reply]
Thanks @backguynn  after removing the label the error get resolved but earlier when i try to send the request to my respective pods(application) it is able to reach but now it is not i didnot make any change just remove the label 

This is my amf_loxilb_serivce.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: amf-loxilb-service
  #namespace: kube-system
  annotations:
    loxilb.io/liveness: "yes" 
    loxilb.io/lbmode: "default"
    loxilb.io/sticky-sessions: "false"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
     app.kubernetes.io/instance: divyamls
     app.kubernetes.io/name: helm-divyam-amf
  ports:
   - port: 38412
     targetPort: 38412
     protocol: SCTP
  type: LoadBalancer
  #externalTrafficPolicy: Local
  sessionAffinity: None
  externalIPs:
          - 20.20.19.69
```
          
          
  Do you have any idea what can be the reason
