### DISCUSSION TITLE
Loxilb Config Issue for AMF pod

### DISCUSSION THREAD

**Discussion by chugh50** [loxilb-io/loxilb#944] [Q&A] [answered]
Hello,I am trying to setup loxilb loadbalancer for amf pods ,So this is my service setup

apiVersion: v1
kind: Service
metadata:
  name: amf-loxilb-service
  #namespace: kube-system
  annotations:
    loxilb.io/liveness: "yes" 
    loxilb.io/lbmode: "onearm"
    loxilb.io/probetype : "sctp"  
    #loxilb.io/probetype: "none"
    loxilb.io/staticIP: "10.10.19.69"
    #loxilb.io/sticky-sessions: "false"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
          #what: amf-app
     app.kubernetes.io/instance: divyamls
     app.kubernetes.io/name: helm-divyam-amf
  ports:
   - port: 38412
     targetPort: 38412
     protocol: SCTP
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  
  So whenever i set some probetype value i get sctp connection request (all procedure) in tcpdump but it didnot reach to my amf pods logs but if i set probetype to none i am able to recieve the sctp connection request in tcpdump as well as in amf logs (and there is no difference in tcpdump of both the cases)
  
can someone look into that why setting probtype giving this error

**Comment by TrekkieCoder** [comment, marked as answer]
Hi @chugh50,

I would suggest you test with a service yaml as follows :
```
apiVersion: v1
kind: Service
metadata:
  name: sctp-lb1
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/usepodnetwork : "yes"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-ds-test
  ports:
    - port: 55003
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-ds-ds
  labels:
    what: sctp-ds-test
spec:
  replicas: 2
  selector:
    matchLabels:
      what: sctp-ds-test
  template:
    metadata:
      labels:
        what: sctp-ds-test
    spec:
      containers:
      - name: sctp-ds-pod
        image: loxilbio/sctp-darn:latest
        command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
        ports:
        - containerPort: 9999
```

Please note that if you kill the pods with kubectl delete pods, the pods are respawned quite fast before loxilb get detect they are even dead. You can also test replicaset size using :
```
kubectl edit deployment sctp-ds-ds
```
And then manually set "replicas" field. Also, feel free to try variations of ```loxilb.io/probetimeout``` and  ```loxilb.io/proberetries```.
