### DISCUSSION TITLE
Loxilb for two amfs

### DISCUSSION THREAD

**Discussion by chugh50** [loxilb-io/loxilb#950] [Q&A] [answered]
Hello,
I am using loxilb loadbalancer for my amf pods.  i am using two gnB and send the ngsetup request and both amf receive ngsetup request and then i send the registration request from both the gnB and respective amf pod recieve it now i crash one of the amf pod and again send the registration request from both the gnB now i want that these registration request handle by running amf but it is not happening 
This is the service i am using 

apiVersion: v1
kind: Service
metadata:
  name: amf-loxilb-service
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/usepodnetwork : "yes"
    loxilb.io/probetype: "none"
    loxilb.io/staticIP: "10.10.19.69"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
          #what: amf-app
     app.kubernetes.io/instance: amantyals
     app.kubernetes.io/name: helm-amf
  ports:
   - port: 38412
     targetPort: 38412
     protocol: SCTP
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  
  
  This is the running command i am using for my loxilb [ "/root/loxilb-io/loxilb/loxilb" , "--ipvs-compat",   "--fallback" ]
  
  If anyone know about this issue please let me know or want to suggest alternative solution

**Comment by TrekkieCoder** [comment, marked as answer]
Request you to try with this yaml for loxilb - 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loxilb-lb
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: loxilb-app
  template:
    metadata:
      name: loxilb-lb
      labels:
        app: loxilb-app
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
      serviceAccountName: kube-loxilb
      containers:
      - name: loxilb-app
        image: "ghcr.io/loxilb-io/loxilb:latest"
        imagePullPolicy: Always
        command:
        - /root/loxilb-io/loxilb/loxilb
        args:
        #- --ipvs-compat
        - --k8s-api=cluster
        - --egr-hooks
        - --fallback
        - --blacklist=cni[0-9a-z]|veth.|flannel.|cali.|tunl.|vxlan[.]calico|kube[-]bridge
        ports:
        - containerPort: 11111
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        env:
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb-egress-service
  namespace: kube-system
  annotations:
    loxilb.io/egress: "yes"
    loxilb.io/probetype: "none"
    loxilb.io/staticIP: "0.0.0.0"
spec:
  type: LoadBalancer
  loadBalancerClass: loxilb.io/loxilb
  externalTrafficPolicy: Local
  selector:
    app: loxilb-app
  ports:
  - name: loxilb-egress
    port: 9999
    targetPort: 9999
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb-lb-service
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    app: loxilb-app
  ports:
  - name: loxilb-app
    port: 11111
    targetPort: 11111
    protocol: TCP
```

This removes the need for using ipvs-compat mode. And also will make sure usepodnetwork to work. Afterwards, kindly try gNB requests again.
