### DISCUSSION TITLE
L7 loxilb setup

### DISCUSSION THREAD

**Discussion by chugh50** [loxilb-io/loxilb#955] [Q&A] [answered]
I am trying to setup L7 loxilb loadbalancing for my amf pods .So i am running two amf pods using replicaset and also configure loxilb with the L7 image and use the following serivce 

kind: Service
metadata:
  name: amf-loxilb-service
  #namespace: kube-system
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/usepodnetwork : "yes"
    loxilb.io/lbmode: "fullproxy"    
    loxilb.io/epselect: "n2"
    loxilb.io/probetype: "none"
    loxilb.io/staticIP: "10.10.19.69"
    #loxilb.io/sticky-sessions: "false"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
          #what: amf-app
     app.kubernetes.io/instance: amantyals
     app.kubernetes.io/name: helm-amf
  ports:
   - port: 38412
     targetPort: 38412
     protocol: SCTP
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None 
  
 Whenever i try to send any request (like sctp connection ,ngsetup) from one gnB it should route to one of the amf but in my case it is routing to both the amf 
 
 If someone have idea about this issue please let me know
 Thanks

**Comment by UltraInstinct14** [comment]
In this mode, the node specific messages are sent to all the available AMFs but UE registration etc is load-balanced to specific AMF.

**Reply by chugh50** [reply]
Hi @UltraInstinct14 Thanks for the input i rechecked as you mentioned but UE registration request is also routing to both amf pods

**Reply by TrekkieCoder** [reply]
LoxiLB L7 currently supports NGAP in ASN.1 APER (aligned Packed Encoding Rules) format only. Can you please confirm in your setup ? And are you using this image : ```ghcr.io/loxilb-io/loxilb:scp``` ?

**Reply by chugh50** [reply]
yes in my setup i am using NGAP in ASN.1 APER and i used the same image only

**Comment by TrekkieCoder** [comment, marked as answer]
I tried a similar setup. The loxilb yaml as follows - 
```
containers:
      - name: loxilb-app
        image: "ghcr.io/loxilb-io/loxilb:scp"
        imagePullPolicy: Always
        command:
        - /root/loxilb-io/loxilb/loxilb
        args:
        - --proxyonlymode
        - --blacklist=cni[0-9a-z]|veth.|flannel.|cali.|tunl.|vxlan[.]calico|kube[-]bridge
```

LB rules - 
```
| 192.168.80.250 |         |      | 38412 | sctp  | amf:llb-inst0                |    0 | n2  | fullproxy | 172.16.219.106 | 38412 |      1 | -     | 14:942   |
|                |         |      |       |       |                              |      |     |           | 172.16.219.121 | 38412 |      1 | -     | 2:126    |
```

Observations -

NGsetup and other node messages are sent to all AMFs but UE messages like InitialUE message are send to a particular AMF only.
