### DISCUSSION TITLE
NGAP Load Balancing with LoxiLB and free5GC (L7 load-balancer)

### DISCUSSION THREAD

**Discussion by williamlin0518** [loxilb-io/loxilb#967] [Q&A] [answered]
I'm trying to implement SCTP load balancing for Free5GC AMF using LoxiLB, but encountering connection issues. Here's my setup:

this is how I implement in very detail [NGAP Load Balancing with LoxiLB using free5GC](https://hackmd.io/mISEMQzbS0-XNW886o7yGQ?both) **this note open to edit!**

welcome any suggestions for improving this setup, corrections to my configurations, or alternative approaches. Feel free to point out if I'm misunderstanding any

If you need any additional information or logs, I'll be happy to provide them.

**Environment**:
- Single Kubernetes cluster running Free5GC components
- LoxiLB running as standalone Docker container
- Two AMF instances
- UERANSIM for testing

**Configuration**:
1. LoxiLB VIP: 10.100.50.249
2. AMF1: 10.100.50.251
3. AMF2: 10.100.50.252
4. SCTP Port: 38412

Current Setup:
1. LoxiLB is deployed and running:
```bash
docker run -u root --cap-add SYS_ADMIN --restart unless-stopped --privileged -dit -v /dev/log:/dev/log --entrypoint=/root/loxilb-io/loxilb/loxilb --net=host --name loxilb ghcr.io/loxilb-io/loxilb:scp --proxyonlymode
```
# Deploy kube-loxilb
1. **loxiURL**: the IP address of the machine running the LoxiLB data-plane and to talk to the external LoxiLB instance.
`Host network IP: 192.168.56.106 (enp0s8)`

```
        args:
        - --loxiURL=http://192.168.56.106:11111
        - --cidrPools=defaultPool=10.100.50.249/32
        #- --monitor
        #- --setBGP=64512
        #- --extBGPPeers=50.50.50.1:65101,51.51.51.1:65102
        #- --setRoles
        - --setLBMode=2
        #- --config=/opt/loxilb/agent/kube-loxilb.conf
```
# Modify the AMF service
Modify the AMF service to use LoadBalancer type and add LoxiLB annotations

`free5gc/values.yaml`

change:
```yaml
  amf:
    n2if:  # NGAP
      ipAddress: 10.100.50.250
    service:
      ngap:
        enabled: false
        name: amf-n2
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
```
to:
```yaml
  amf:
    n2if:  # NGAP
      ipAddress: 10.100.50.251
    service:
      ngap:
        enabled: true
        name: amf-n2
        port: 38412
        protocol: SCTP
        type: LoadBalancer
        loadBalancerClass: "loxilb.io/loxilb"  # 
        annotations:
          loxilb.io/probetype: "none"
          loxilb.io/lbmode: "fullproxy"
          loxilb.io/epselect: "n2"
          loxilb.io/lbclass: "loxilb.io/loxilb" 
  amf2:
    n2if:  # NGAP
      ipAddress: 10.100.50.252
    service:
      ngap:
        enabled: true
        name: amf2-n2
        port: 38412
        protocol: SCTP
        type: LoadBalancer
        loadBalancerClass: "loxilb.io/loxilb"  # 
        annotations:
          loxilb.io/probetype: "none"
          loxilb.io/lbmode: "fullproxy"
          loxilb.io/epselect: "n2"
          loxilb.io/lbclass: "loxilb.io/loxilb" 
```
 
## gnb can't find AMF
###have no ct
```
vboxuser@test1000:~/work/free5gc-helm/charts$ docker exec -it loxilb loxicmd get lb -o wide
|    EXT IP     | SEC IPS | HOST | PORT  | PROTO |                        NAME                         | MARK | SEL |   MODE    | ENDPOINT  | EPORT | WEIGHT | STATE | COUNTERS |
|---------------|---------|------|-------|-------|-----------------------------------------------------|------|-----|-----------|-----------|-------|--------|-------|----------|
| 10.100.50.249 |         |      | 38412 | sctp  | free5gc_free5gc-helm-free5gc-amf2-amf2-n2:llb-inst0 |    0 | n2  | fullproxy | 10.0.2.15 | 31413 |      1 | -     | 0:0      |


vboxuser@test1000:~/work/free5gc-helm/charts$ docker exec -it loxilb loxicmd get ct
| SERVICE NAME | DESTIP | SRCIP | DPORT | SPORT | PROTO | STATE | ACT | PACKETS | BYTES |
|--------------|--------|-------|-------|-------|-------|-------|-----|---------|-------|
```
### so I create lb by my own and still can't establish connection
```
docker exec -it loxilb loxicmd create lb 10.100.50.249 --sctp=38412:38412 --endpoints=10.100.50.251:1,10.100.50.252:1 --mode=fullproxy
```

```
vboxuser@test1000:~/work/free5gc-helm$ docker exec -it loxilb loxicmd create lb 10.100.50.249 --sctp=38412:38412 --endpoints=10.100.50.251:1,10.100.50.252:1 --mode=fullproxy

ProtoPortpair: map[sctp:[38412:38412]]
Debug: response.StatusCode: 200
Success
vboxuser@test1000:~/work/free5gc-helm$ docker exec -it loxilb loxicmd get lb -o wide
|    EXT IP     | SEC IPS | HOST | PORT  | PROTO |                        NAME                         | MARK | SEL |   MODE    |   ENDPOINT    | EPORT | WEIGHT | STATE | COUNTERS |
|---------------|---------|------|-------|-------|-----------------------------------------------------|------|-----|-----------|---------------|-------|--------|-------|----------|
| 10.100.50.249 |         |      | 38412 | sctp  | free5gc_free5gc-helm-free5gc-amf2-amf2-n2:llb-inst0 |    0 | rr  | fullproxy | 10.100.50.251 | 38412 |      1 | -     | 0:0      |
|               |         |      |       |       |                                                     |      |     |           | 10.100.50.252 | 38412 |      1 | -     | 0:0      |
vboxuser@test1000:~/work/free5gc-helm$ 
```

### Questions:

1. Is my LoxiLB configuration correct for SCTP load balancing?
1. Why isn't the SCTP connection being established through the VIP?

1. the way I duplicate amf may wrong? like use NodePort instead of LoadBalancer type for AMF services?
