### DISCUSSION TITLE
Using Loxi LB to provision Load Balancers for a Kubernetes Cluster

### DISCUSSION THREAD

**Discussion by bewdycodebase** [loxilb-io/loxilb#985] [General]
So the idea was to deploy loxiLB with the below behavior 

Watches kubernetes cluster for LoadBalancer service types 

Assigns a publicly assignable public IP to the LoadBalancer in kubernetes

Currently loxiLB assigns the LoadBalancer a non public IP address and then the LoadBalancer can be accessed using the loxiLB Node IP at a specific port

Issue with is that I cannot directly register an A name with an IP like 1.1.1.1:50004 were 1.1.1.1 is the IP of the node where loxiLB is hosted

Has anyone done something similar?

**Comment by inhogog2** [comment]
Hi @bewdycodebase ,

It is also possible to register a public IP address directly using "loxilb.io/staticIP" annotation.

Below is an example of "loxilb.io/staticIP", so you can use the staticIP annotation.

```
apiVersion: v1
kind: Service
metadata:
  name: sctp-lb-fullnat
  annotations:
    loxilb.io/lbmode: "fullnat"
    loxilb.io/staticIP: "1.1.1.1"
spec:
  loadBalancerClass: loxilb.io/loxilb
  externalTrafficPolicy: Local
  selector:
    what: sctp-fullnat-test
  ports:
   - port: 50004
     protocol: SCTP
     targetPort: 9999
  type: LoadBalancer
```
