### ISSUE TITLE
Support LC distribution

### ISSUE THREAD

**Issue by UltraInstinct14** [loxilb-io/loxilb#481]
loxilb currently supports RR, WRR distribution but in many cases LC (least connections) become necessary.

**Comment by TrekkieCoder** [comment]
The initial support is added. To configure using loxicmd - 

```
loxicmd create 20.20.20.1 --tcp=2020:8080 --endpoints=31.31.31.1:1,32.32.32.1:1,33.33.33.1:1 --select lc
```

To configure using kube-loxilb, use the following yaml - 

```
apiVersion: v1
kind: Service
metadata:
  name: sctp-lb
  annotations:
    loxilb.io/lbmode: "fullnat"
    loxilb.io/epselect : "lc"
    spec:
  loadBalancerClass: loxilb.io/loxilb
  externalTrafficPolicy: Local
  selector:
    what: sctp-lb
  ports:
   - port: 56004
     protocol: SCTP
     targetPort: 9999
  type: LoadBalancer
```
