### ISSUE TITLE
Configure end-point probe-time,retry values etc from kube-loxilb

### ISSUE THREAD

**Issue by UltraInstinct14** [loxilb-io/loxilb#546]
**Is your feature request related to a problem? Please describe.**
Currently, some values needed to configure end-points like probing timer and retry values need to be manually configured using loxicmd. Otherwise the default values in loxilb are used which may not be suitable for everyone.

**Describe the solution you'd like**
When using kube-loxilb, one should be able to specify default values using some annotation

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TrekkieCoder** [comment]
The support has been added.  The service can be configured with the following annotations -

```
apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  annotations:
    loxilb.io/lbmode: "fullnat"
    loxilb.io/liveness: "yes"
    loxilb.io/probetimeout: "10"
    loxilb.io/proberetries: "2"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: the
  ports:
    - port: 55001
      targetPort: 5001
  type: LoadBalancer
```   

In the above example, there will be two retries in interval of 10 seconds before considering the end-point as inoperative.
