### ISSUE TITLE
/opt/loxilb/dp/bpf/nat_map config is null with externalCIDR set to 0.0.0.0

### ISSUE THREAD

**Issue by Rammurthy5** [loxilb-io/loxilb#949]
**Describe the bug**
when we want to use multiple loxi docker instances acting up as master, we configure `externalCIDR` param in kube-loxi as `0.0.0.0/32`.

**To Reproduce**
Create two Loxi docker instances and use their ip in kube-loxilb as below. Deploy a service with `lbmode` as `onearm`. 

```
- --loxiURL=http://<IP_OF_LOXI_1>:11111/,http://<IP_OF_LOXI_2>:11111/
        - --externalCIDR=0.0.0.0/32
        - --setLBMode=2
```
       
**Expected behavior**
Add appropriate config in /opt/loxilb/dp/bpf/nat_map to egress the packets Out. 

**Environment (please complete the following information):**
 - OS: ubuntu 22.04 LTS
 - Kernel Version: [e.g. 5.4.1, 5.15.5]
 - LoxiLB Version:   imageID 2b22518d4161
 - Cloud Environment: aws
 - K8s Version 1.29

**Comment by TrekkieCoder** [comment]
For this to work, the service needs to have  ```loxilb.io/lbmode: "hostonearm"``` annotation.  For example - 
```
apiVersion: v1
kind: Service
metadata:
  name: tcp-lb
  annotations:
    loxilb.io/lbmode: "hostonearm"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: tcp-lb-test
  ports:
    - port: 55003
      targetPort: 80
  type: LoadBalancer
```

Please give it a try.
